stages:
  preprocess:
    cmd: python -m src.data
    deps:
      - src/data.py
      - src/__init__.py
      - news.csv
    outs:
      - data_processed/

  train:
    cmd: python -m src.train
    deps:
      - src/train.py
      - src/model.py
      - src/data.py
      - src/__init__.py
      - data_processed/
    outs:
      - best_model.pt
      - training_plot.png
      - runs/

  evaluate:
    cmd: python -m src.evaluate
    deps:
      - src/evaluate.py
      - src/model.py
      - src/data.py
      - src/__init__.py
      - best_model.pt
      - data_processed/
    outs:
      - predictions_on_test.txt
      - docs/attention_examples/
    metrics:
      - evaluation_results/rouge_scores.json 