stages:
  preprocess:
    cmd: python -m src.data
    deps:
      - src/data.py
      - src/__init__.py
      - news.csv
    outs:
      - data_processed/

  train:
    cmd: python -m src.train --epochs 3 --no-resume
    deps:
      - src/train.py
      - src/model.py
      - src/data.py
      - src/__init__.py
      - data_processed/
    outs:
      - best_model_pretrained.pt
      - best_model_random.pt
      - training_plot_pretrained.png
      - training_plot_random.png
      - model_info_pretrained.json
      - model_info_random.json
      - checkpoints/

  evaluate:
    cmd: python -m src.evaluate
    deps:
      - src/evaluate.py
      - src/model.py
      - src/data.py
      - src/__init__.py
      - best_model_pretrained.pt
      - data_processed/
    outs:
      - predictions_on_test.txt
      - docs/attention_examples/
    metrics:
      - evaluation_results/rouge_scores.json 